index.js, lib/assertions.js, lib/crypto.js, lib/express.js, package-lock.json, package.json, static/myinfo.json
Given the generally long process of onboarding onto MyInfo and its regular maintenance schedules, it is generally helpful to have a mock service that can stand in for the real thing. MockInfo is built on top of MockPass and is backed by a static file generated from the list of known test personas provided by the MyInfo team.
MockInfo includes functionality that mimics the person and person-basic endpoints and the typical consent flow for a user. It features both TUO authorization available to government systems and token-based authorization required for most other applications.
See commits for further details
=> Implement MockInfo

README.md, index.js, lib/assertions.js, lib/express/spcp.js, package-lock.json, package.json, static/saml/unsigned-assertion.xml, static/saml/unsigned-response.xml
- Made  singing/encryption optional
- Fixed some bugs of  the response templates
- Url encoded the artifactId
- Set `issueInstant` to utc time now.
=> Make signing/encryption optional and fix some template issues

lib/assertions.js, lib/express/spcp.js, static/saml/unsigned-assertion.xml
For deployment in multiple environments, there's a need to allow the recipient value in the Assertion to be configurable.
Simplify the assertion template creation to always create the template for every POST call to spcp. This would ensure that the 'issueInstant' field is always set with the latest date and time.
=> Allow configurable assertion recipient field. Simplify assertion template creation

lib/assertions.js, lib/express/spcp.js, static/saml/unsigned-assertion.xml, static/saml/unsigned-response.xml
Using Spring Security SAML (https://projects.spring.io/spring-security-saml/) for a web application currently fails when using MockPass as Spring Security SAML performs some validation against the ArtifactResponse.
- Removed SERVICE_PROVIDER_RECIPIENT as the recipient in SubjectConfirmationData should tally with the service provider's assertion consumer service url.
- Set the destination in the ArtifactResponse to tally with the service provider's assertion consumer service url.
- Added SERVICE_PROVIDER_ENTITY_ID to populate the Audience in AudienceRestriction.
- Set InResponseTo to the request ArtifactResolve ID.
- Set Issuer to the IDP ID.
This pull request has been validated against a sample webapp using spring-security-saml2-core 1.0.9.RELEASE.
=> Use variables to populate templates in order to pass SAML validation

README.md, index.js, lib/assertions.js, lib/express/spcp.js
This PR allows assertion endpoint to be specified using the `PartnerId` request query parameter, similar to actual SPCP behaviour.
This allow a MockPass deployment to support testing of different IDP URLs simply by varying the `PartnerId` in the URL request query parameter, instead of changing environment variable.
Other improvements:
* Added additional test accounts
* Improved 'combobox' values for CorpPass credentials in login page in instead of `[object Object]`.
=> Allow assertion endpoint to be specified using request parameter

lib/express/myinfo.js
The old approach of adding the hostname and port does not work in a docker-compose network environment. Using express's 'host' param allows us to get both the hostname and port that was used by the request object, solving our problem altogether.
=> Remove hostPort tech debt

lib/express/oidc.js
Currently the implementation is generating a response where the id_token is in JWE JSON Serialization format
```json
{
"access_token":"",
"refresh_token":"refresh",
"scope":"openid",
"token_type":"bearer",
"id_token":{
"recipients":[
{
"encrypted_key":"Y1rLhHgH3MmIpHEduPwZ04OFOoUDLieDsrtKajFNGVJeL6lnB1c-6Emc8uPK9Gmx43M2boHQCGbMEh1hrRIyb2F27MOwD_nBN18BNMFacEEKX5UsU3ItqAhDWkcqg48r3xjD3b2d58Wi5STCP5KizJMxXnBs2qRFZftAdT9pMIQXl3By32iWjdOUtSr7KZq2ZDv6LsODICwkI32Vl1hDDDcp5KdqsBCo4Dz-voVBH-l6-ruAbQTpFlLOfCRWwAO5ZiO2Vx0krUuoFeQf0WL51GAGIb1TUPjI5BqLiJmiaY4E91DveDiQgNwyHxqtgCNU1DZ8a0Yl3KkmUhFoJi04Ww"
}
],
"protected":"eyJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiUlNBLU9BRVAiLCJraWQiOiJiemEwZFhmNkZqbGExRlFyVkttQVR1WmI5LTRNOTBMeER1ZjN1akxZYnFnIn0",
"iv":"2ARSycwYYYq2ksbRUGixEQ", …
```
=> fix: id_token serialization format should be in JWE Compact Serialization format

lib/express/oidc.js, package-lock.json, package.json
Add basic support for handling the nonce sent with the oidc authentication request by setting it in the token response.
This implementation stores the nonce keyed by authorization codes that is generated by the server in memory. The nonces will be cleared from memory after 5 minutes from the authentication request after the next token response is issued by the server.
=> feat: add nonce handling for oidc authentication request

lib/express/oidc.js
**Background**
Using Spring Security's OpenID Connect support for building a web application.
**Issue**
Spring Security's OpenID Connect support throws exceptions when handling the token response from mockpass.
**Fixes**
- According to the spec the issuer should be a uri "contains scheme, host, and optionally, port number and path components and no query or fragment components". So the code was changed to include the scheme.
- The Spring Security implementation currently throws an exception if the access_token is empty. So the code was changed to a hardcoded value 'access'. Not sure if this will impact other relying party implementations.
=> fix(oidc): fix token values to pass relying party validations

lib/express/spcp.js, static/saml/unsigned-response.xml
Hi,
We're working on SingPass integration in our LMS, and we've used mockpass to get working prototype.
Our LMS uses [simplesamlphp library](https://github.com/simplesamlphp/simplesamlphp) v1.18.7.
During prototyping, I've found two issues in mockpass which affect simplesamlphp SAML implementation:
- `samlp:ArtifactResponse` should have two `Status` elements - one is `Response` child, another is in `ArtifactResponse` - see SAML standard, e.g. https://logius.nl/sites/default/files/public/bestanden/diensten/Routeringsvoorziening/eID%20SAML%204.4%20-%20Specification-v8-20200309_110046.pdf
- `RelayState` query parameters becomes `"undefined"` when service provider doesn't send `Target` parameter - but it should be skipped instead
This PR fixes simplesamlphp integration issues.
=> Simplesamlphp integration fixes

lib/express/myinfo/consent.js, lib/express/oidc.js, lib/express/saml.js, static/html/login-page.html
This PR aims to add functionality to allow users to key in a custom NRIC instead of using the predefined ones. (SAML-only)
The use-case is that the SP may already have seeded data that uses different NRICs from the ones provided in mockpass, so it would be nice for a custom input.
I'm relatively new to SAML, and the code is the shortest path I could think of to achieve this functionality - please let me know if it is necessary to generate and read SAML Artifacts for this feature, thanks!
=> add form for custom NRIC for singpass login (SAML)

lib/express/oidc.js
Per the documentation here: https://public.cloud.myinfo.gov.sg/sglogin/SingPass-login-specs-v0.1.html#operation/tokenAuth
The token endpoint returns an expires_in in the response, so i've added the expires_in of 1 day in seconds (to be consistent with the token lifespan)
=> feat: Add expires_in to POST /token response

lib/assertions.js, lib/express/oidc.js
Reference: https://public.cloud.myinfo.gov.sg/sglogin/SingPass-login-specs-v0.1.html
- Adds refresh_token based on specification for Singpass OIDC (40 chars long)
- Adds rt_hash so that the refresh token can be validated against at the RP before refreshing the token, as recommended by the docs
=> feat: add refresh_token and rt_hash to singpass oidc

lib/express/myinfo/consent.js
When there is an error during the MyInfo consent flow, e.g. if the user does not provide consent, MyInfo returns `error-description` (note hyphen) in the query params, as shown in the screenshots below. However, Mockpass returns `error_description` (note underscore).
Change `error_description` to `error-description`.
=> fix: change error_description to error-description

lib/assertions.js, lib/express/oidc.js
Adds functionality when "grant_type=refresh_token" so that the tokens can be refreshed on the `/token` endpoint, in addition to the current functionality of creating tokens on first login. 
This is based on https://public.cloud.myinfo.gov.sg/sglogin/SingPass-login-specs-v0.1.html
Prefixes refresh_token with uuid for simplicity's sake so that we can retrieve the corresponding nric for the new tokens.
- This is separated by '/' (with an additional padding of 'f' if the uuid is an even number, so to keep with the length of 40 characters (20 bytes))
=> Adds handling of grant_type=refresh_token to token endpoint (oidc)

lib/assertions.js
According to spec, `iat` and `exp` should be `NumericDate`s, i.e. number of seconds (not millis) from epoch.
Ref: https://datatracker.ietf.org/doc/html/rfc7519#section-4.1
=> fix: make ID token time claims spec compliant

lib/express/myinfo/consent.js, lib/express/oidc.js, lib/express/saml.js, lib/express/sgid.js, lib/saml-artifact.js, public/mockpass/resources/js/login-common.js, static/html/login-page.html
#142 added support for custom NRICs for SAML login, but used the raw NRIC as the SAML artifact. The resultant artifact is 6 bytes instead of the standard 44 bytes, making it non spec compliant. This makes it problematic for use in libraries - e.g. Spring Security SAML, which does length and partner ID validation on the artifact, rejects the artifact altogether before even attempting an artifact exchange.
This PR fixes the issue by generating a proper 44-byte artifact upon form submission:
```
base64('00040000' + hashedPartnerId + hex('customNric:' + customNric))
```
Updated both SAML and Myinfo assert endpoints to accept the new artifact format.
=> fix: make custom NRIC SAML artifact spec compliant

lib/express/sgid.js
- SGID uses JWE compact encryption. 
- The sub should be consistent between access token and id token.
- SGID encrypts myinfo details using the client-provided public key.
- Use JWE compact encrpytion format.
- Align sub to be the same for both id token and access token
- Use client-provided `key.pub` to encrypt myinfo details.
=> fix(sgid): use compact encrypt for jwe, modify jwt sub

README.md, index.js, lib/express/oidc.js, lib/express/saml.js, lib/express/sgid.js
- Mockpass is very suitable as a mock Singpass server for writing E2E tests against, except for the HTML login page
- We can set the `SHOW_LOGIN_PAGE` environment variable to `false` to overcome this, but then it becomes less suitable for manual testing
- We then need to maintain two separate configurations / instances of Mockpass, one for automated E2E tests, and another for manual tests
- Allow the `showLoginPage` config to be overridden per request via an `X-Show-Login-Page` HTTP header
- This way, E2E tests can send `X-Show-Login-Page: false` in the request, while manual testing can still be done in the browser, all against the same running instance of Mockpass
=> feat: allow overriding `showLoginPage` config via request header

README.md, index.js, lib/assertions.js, lib/auth-code.js, lib/express/myinfo/consent.js, lib/express/oidc.js, lib/express/saml.js, lib/express/sgid.js, lib/saml-artifact.js, public/mockpass/resources/js/login-common.js, static/html/login-page.html, static/myinfo/v3.json
- Mockpass offers only limited support for custom identities. Users are mostly locked into a fixed set of identities to choose from. This limits its usefulness as a mock server for writing E2E tests against. Custom NRIC support was added in #142, but this was only for the SAML implementations.
- The OIDC implementations return a single integer (the index) as the user UUID (e.g. `s=S8979373D,u=0` instead of `s=S8979373D,u=a9865837-7bd7-46ac-bef4-42a76a946424` in the `sub` claim). This integer index is not realistic test data as it is not a UUID.
**Features**:
- Allow specifying custom NRIC/UUID/UEN via login form or HTTP headers
- Consistent support for both OIDC and SAML
**Improvements**:
- Return realistic UUID in OIDC implementations
- Support OIDC refresh tokens for Corppass
**Bug …
=> feat: allow custom identities

lib/assertions.js
based on the latest CorpPass spec (v1.3), there is a `EntityInfo` claim in the assertion which contains the UEN. This was missing in mockpass and thus we couldn't handle CorpPass logins properly in development.
**Bug Fixes**:
- add `entityInfo` to CorpPass `idTokenClaims`
=> add entityInfo to corppass

lib/crypto/myinfo-signature.js, lib/express/myinfo/controllers.js
Fixes #457
cc @randName for review
=> fix(myinfo): generate base string straight from params

lib/crypto/myinfo-signature.js
paiseh, overlooked the request body. `Object.assign` works on nullish values so no need for a guard.
Closes #457 properly this time
=> include request body in params

lib/express/sgid.js
As sgID and its SDK mature, add `/.well-known/openid-configuration` so that clients (sgID, OpenID and others) can consume it if running on local development machines
=> feat(sgid): add `/.well-known/openid-configuration`

.eslintrc.json, lib/auth-code.js, lib/express/sgid.js
Enables sgID tokens to store information about OAuth scopes, and thus query for them.
Closes #539
- Associated the requested scopes with each authcode.
- In `/userinfo` request, use requested scopes to obtain the equivalent MyInfo fields. This is not a 1-1 conversion with MyInfo as not all fields are officially documented yet.
**Features**:
The user can query for more sgID OAuth scopes than previously allowed.
Ideally I should write some tests for this. However, I can say I've tested on my local FormSG with sgID integration and this MockPass indeed works.
=> feat(sgid): Respect OAuth scopes

lib/express/oidc/v2-ndi.js
Currently the error responses do not conform to the relevant RFCs.
This updates the error responses to conform to the spec
Authorization Response
- https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1
Access Token Response
- https://datatracker.ietf.org/doc/html/rfc6749#section-5.2
- https://datatracker.ietf.org/doc/html/rfc7521#section-4.2.1
- https://datatracker.ietf.org/doc/html/rfc7523#section-3.2
=> feat: use spec compliant error responses for ndi oidc

lib/express/myinfo/controllers.js, package-lock.json, package.json
Replace node-jose package with jose for myInfo SSO.
Addresses part of Issue #328 
Left to resolve use of library in sgID, spcp and v2-ndi files.
Replace node-jose with jose library for encryption and signing of data.
=> refactor(myinfo): replace node-jose with jose for SSO

lib/express/oidc/v2-ndi.js, static/certs/oidc-v2-asp-public.json, static/certs/oidc-v2-asp-secret.json
This refactors the `ndi` implementation to use `jose`, add additional logging and fix some bugs.
This should also close #594
=> refactor(ndi): use jose

lib/express/sgid.js
sgID is a government identity provider that provides Myinfo data.
There are missing some fields that sgID is supporting, hence, RP is not able to test them.
Add the following scopes:
```
'myinfo.birth_country',
'myinfo.vehicles',
'myinfo.name_of_employer',
'myinfo.workpass_status',
'myinfo.workpass_expiry_date',
'myinfo.marital_status',
'myinfo.mobile_number_with_prefix',
```
Default missing fields to `NA` instead of undefined.
=> feat: add more sgid scopes

lib/express/oidc/v2-ndi.js
=> fix(ndi): fix incorrect key selection for ecdh-es

lib/express/oidc/v2-ndi.js
After refactor of the NDI implementation to use `jose` library in #595, `kid` is no longer being set on the ID token JWS header. This is breaking verification of the ID token JWS, as RPs need to select the appropriate key from the OP JWKS based on the `kid` value for verification.
Accessing `signingKey.kid` doesn't work as `signingKey` is from `jose.importJWK()`, which is a generic `crypto` library [`KeyObject`](https://nodejs.org/api/crypto.html#class-keyobject) that isn't aware of JWK and so doesn't have the concept of the `kid`. In the [implementation prior to refactor](https://github.com/opengovsg/mockpass/blob/v4.0.8/lib/express/oidc/v2-ndi.js#L291C54-L300) the `signingKey` appears to be some kind of JWK-aware thing so it had the `kid`.
Closes #604 
**Bug Fixes**:
- When constructing …
=> fix(ndi): fix missing kid on JWS header

README.md, app.js, lib/auth-code.js, lib/express/myinfo/consent.js, lib/express/oidc/spcp.js, lib/express/oidc/v2-ndi.js, lib/express/sgid.js
For stateless environments where we cannot guarantee the state of a process, such as AWS Lambda or Netlify Functions, allow auth code and token generation to be base64url encodings of the values they are meant to represent, rather than random characters
=> feat: allow stateless operation with base64url-encoded tokens

static/myinfo/v3.json
- Mockpass' sgID userinfo endpoint response has residentialstatus as `Citizen`, but production sgID response has `CITIZEN`
- Similarly Myinfo v3 API docs' example has `CITIZEN` in the desc field for this case
(I don't know if the other values like `PR` are correct. Also production sgID returns `NA` for foreigners, and not `ALIEN`, but mockpass doesn't have personas that reflect that right now and I'm not sure how the real Myinfo v3 handles it.)
**Bug Fixes**:
- Update myinfo personas file to replace the desc string from `Citizen` to `CITIZEN` where residentialstatus has code `C`.
=> fix: wrong desc when residentialstatus is code=C

.husky/install.mjs, .husky/pre-commit, .husky/pre-push, package-lock.json, package.json
Remove boilerplate from hook files.
Move husky install from postinstall to prepare, to match current husky init behaviour.
Use husky's [suggested script](https://typicode.github.io/husky/how-to.html) to avoid errors for npm installs without devDependencies.
=> chore: upgrade husky setup for v9

README.md, lib/express/sgid.js, static/myinfo/v3.json
Mockpass currently doesn't support sgID clients requesting for the `pocdex.public_officer_details` scope, `"NA"` is always returned.
(It also doesn't support `pocdex.number_of_employments`, but I don't seem to receive that value from sgID, so I don't want to blindly emulate it without knowing what the real values are.)
**Features**:
- Supporting adding an `publicofficerdetails` array to personas to serve those details to sgID clients asking for `pocdex.public_officer_details`
Example of info to add to persona:
```
"publicofficerdetails": [
{
"work_email": "lim_yong_xiang@was.gov.sg",
"agency_name": "Work Allocation Singapore",
"department_name": "Allocation Central",
"employment_type": "Fixed Term",
"employment_title": "Senior Software Engineer - LLv1 (Individual Contributor) (WAS)"
}
] …
```
=> feat: sgID support for pocdex.public_officer_details

Dockerfile
FormSG is currently using v4.04 of mockpass however when upgrading mockpass to latest (v4.3.0) there is an error when running docker compose because .husky is not copied so when we run npm ci .husky directory does not exist causing docker build image to fail
I copy the .husky directory first to ensure when I run npm ci the prepare script in package.json can run successfully
=> fix(docker): copy .husky during docker build

lib/assertions.js
https://stg-id.singpass.gov.sg/docs/authorization/api,  Regular NRIC holders sub claim content include NRIC and UUID (eg. s=S1234567A,u=32af8b7d-ad1d-4c25-8dc7-0a981b533000) 
Singpass Foreign Account holders sub claim content include: Singpass User ID (UID), Foreigner ID (FID), Country-of-Issuance (COI) and UUID (e.g. s=Y7613265T,fid=G730Z-H5P96,coi=DE,u=e2af740e-25b4-4b19-b527-494670952cb0)
Closes [insert issue #]
_How did you solve the problem?_
=> Update assertions.js to support SFA

lib/express/myinfo/controllers.js
1. In myinfo docs (Developers_FAQ.pdf), noted use of A256GCM
2. Q15 of https://api.singpass.gov.sg/library/myinfo/developers/FAQ
3. current product integration with myinfo test api is also using A256GCM and it is working
1. Update A128CBC-HS256 to A256GCM
=> fix: myinfo encryptedAndSignedPersona to use enc A256GCM
